# Generated by Django 5.2.5 on 2025-09-03 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], max_length=7, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='diveclub',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diveclub',
            name='pending_members',
            field=models.ManyToManyField(blank=True, related_name='pending_club_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diveclub',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.language'),
        ),
        migrations.AlterField(
            model_name='diveevent',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.language'),
        ),
        migrations.AlterField(
            model_name='divelocation',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.language'),
        ),
    ]
