# Generated by Django 5.2.5 on 2025-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_language_diveclub_admins_diveclub_pending_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], max_length=2, unique=True),
        ),
    ]
