# Generated by Django 5.2.5 on 2025-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_language_name_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='diveclub',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diveclub',
            name='website',
            field=models.URLField(blank=True, help_text="Enter the full URL, including 'http://' or 'https://', e.g., https://example.com"),
        ),
    ]
