# Generated by Django 5.2.5 on 2025-09-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_diveclub_slug_alter_diveclub_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='diveevent',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.diveclub'),
        ),
        migrations.AlterField(
            model_name='diveevent',
            name='max_participants',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
