# Generated by Django 5.2.5 on 2025-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_diveevent_club_alter_diveevent_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='diveevent',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Mark if the dive has been cancelled.'),
        ),
    ]
