# Generated by Django 5.2.5 on 2025-09-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_diveevent_is_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveLocationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_name', models.CharField(blank=True, max_length=255)),
                ('suggested_description', models.TextField(blank=True)),
                ('suggested_country', models.CharField(blank=True, max_length=128)),
                ('suggested_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='website.divelocation')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
