# Generated by Django 5.2.5 on 2025-09-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_divelocationsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diveclub',
            name='language',
        ),
        migrations.RemoveField(
            model_name='diveclub',
            name='location',
        ),
        migrations.RemoveField(
            model_name='diveclub',
            name='name',
        ),
        migrations.AddField(
            model_name='diveclub',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Short abbreviation for the club', max_length=10),
        ),
        migrations.AddField(
            model_name='diveclub',
            name='country',
            field=models.CharField(blank=True, help_text='Nation or country where the club is based', max_length=128),
        ),
        migrations.AddField(
            model_name='diveclub',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveclub',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='diveclub',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diveclub',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DiveClubTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Translated name of the club', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Translated description of the club')),
                ('dive_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.diveclub')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.language')),
            ],
            options={
                'unique_together': {('dive_club', 'language')},
            },
        ),
    ]
