# Generated by Django 5.2.5 on 2025-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_diveclub_language_remove_diveclub_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diveclub',
            name='abbreviation',
        ),
        migrations.AlterField(
            model_name='diveclub',
            name='website',
            field=models.URLField(blank=True, help_text="Enter the full URL, including 'http://' or 'https://', e.g., https://scubaclub.org"),
        ),
    ]
