# Generated by Django 5.2.5 on 2025-09-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_diveclub_abbreviation_alter_diveclub_website'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diveclubtranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='diveclub',
            name='description',
        ),
        migrations.RemoveField(
            model_name='diveclub',
            name='slug',
        ),
        migrations.AddField(
            model_name='diveclubtranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug for this translation'),
        ),
        migrations.AlterUniqueTogether(
            name='diveclubtranslation',
            unique_together={('dive_club', 'language', 'slug')},
        ),
    ]
