# Generated by Django 5.2.5 on 2025-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_diveclubtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diveclub',
            old_name='street',
            new_name='address',
        ),
    ]
