# Generated by Django 5.2.5 on 2025-09-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_street_diveclub_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diveclubtranslation',
            unique_together={('dive_club', 'language')},
        ),
    ]
