# Generated by Django 5.2.5 on 2025-09-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_diveclubtranslation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text="ISO 3166-1 alpha-3 country code (e.g., 'NLD' for Netherlands)", max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['iso_code'],
            },
        ),
        migrations.AlterField(
            model_name='diveclub',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where the club is based', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.country'),
        ),
        migrations.AlterField(
            model_name='divelocation',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where the location is based', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.country'),
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Translated name of the country', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.language')),
            ],
            options={
                'unique_together': {('country', 'language')},
            },
        ),
    ]
