# Generated by Django 5.2.5 on 2025-09-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_country_alter_diveclub_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divelocation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='divelocation',
            name='name',
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='target_language',
            field=models.ForeignKey(default=1, help_text='Language for this suggestion', on_delete=django.db.models.deletion.CASCADE, to='website.language'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiveLocationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Translated name of the location', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Translated description of the location')),
                ('slug', models.SlugField(blank=True, help_text='URL slug for this translation')),
                ('dive_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.divelocation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.language')),
            ],
            options={
                'unique_together': {('dive_location', 'language')},
            },
        ),
    ]
