# Generated by Django 5.2.5 on 2025-10-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_divelocation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divelocationsuggestion',
            name='suggested_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.country'),
        ),
    ]
