# Generated by Django 5.2.5 on 2025-10-03 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_divelocationsuggestion_suggested_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveevent',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dives', to='website.diveclub'),
        ),
        migrations.AlterField(
            model_name='diveevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='dives', to=settings.AUTH_USER_MODEL),
        ),
    ]
