# Generated by Django 5.2.5 on 2025-10-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_diveevent_club_alter_diveevent_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_bottom_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_dangers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_max_depth',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_nicknames',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_parking',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_sight',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationsuggestion',
            name='suggested_type_of_water',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='address',
            field=models.TextField(blank=True, help_text='Translated address details for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='bottom_type',
            field=models.TextField(blank=True, help_text='Translated bottom type description for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='dangers',
            field=models.TextField(blank=True, help_text='Translated dangers or warnings for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='max_depth',
            field=models.TextField(blank=True, help_text='Translated max depth information for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='nicknames',
            field=models.TextField(blank=True, help_text='Translated nicknames or alternative names for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='parking',
            field=models.TextField(blank=True, help_text='Translated parking information for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='sight',
            field=models.TextField(blank=True, help_text='Translated sight or visibility details for the location'),
        ),
        migrations.AddField(
            model_name='divelocationtranslation',
            name='type_of_water',
            field=models.TextField(blank=True, help_text='Translated type of water description for the location'),
        ),
    ]
