# .github/workflows/deploy.yml
name: deploy

on:
  # workflow_run:
  #   workflows: ["Build"]
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  deploy-prd:
    runs-on: ubuntu-latest
    environment: prd
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        # - name: Set up Python
        #   uses: actions/setup-python@v5
        #   with:
        #     python-version: '3.13'

        # - name: Install dependencies
        #   run: |
        #     python -m pip install --upgrade pip
        #     pip install -r requirements.txt

        - name: Get runner public IP
          id: ip
          run: echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

        # https://www.scaleway.com/en/developers/api/kubernetes/#path-access-control-list-add-new-acls
        - name: Add runner IP to Scaleway K8s ACL
          env:
            SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
            SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
            K8S_CLUSTER_ID: ${{ secrets.K8S_CLUSTER_ID }}
          run: |
            curl -X POST \
              -H "X-Auth-Token: $SCW_SECRET_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"rules\":[{\"ip\":\"${{ steps.ip.outputs.ip }}\",\"description\":\"github-actions-runner\"}]}" \
              "https://api.scaleway.com/k8s/v1/regions/$SCW_DEFAULT_REGION/clusters/$K8S_CLUSTER_ID/acls"

        - name: Wait for ACL propagation
          run: sleep 10

        - name: Set up kubectl
          run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/

        - name: Configure kubeconfig
          env:
            KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
          run: |
            echo "$KUBECONFIG_CONTENT" > kubeconfig
            export KUBECONFIG=$PWD/kubeconfig
          
        - name: Rollout restart deployment
          run: |
            kubectl rollout restart deployment scubaclub -n scubaclub

        - name: Force delete kubectl binary
          run: |
            sudo rm -f /usr/local/bin/kubectl

        - name: Remove runner IP from Scaleway K8s ACL
          if: always()
          env:
            SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
            SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
            K8S_CLUSTER_ID: ${{ secrets.K8S_CLUSTER_ID }}
          run: |
            curl -X DELETE \
              -H "X-Auth-Token: $SCW_SECRET_KEY" \
              -H "Content-Type: application/json" \
              -d "{\"acl_rule_ips\":[\"${{ steps.ip.outputs.ip }}\"]}" \
              "https://api.scaleway.com/k8s/v1/regions/$SCW_DEFAULT_REGION/clusters/$K8S_CLUSTER_ID/acls"
