name: publish helm chart

on:
  push:
    branches: [ main, master ]
    paths:
      - 'helm/scubaclub/**'
      - '.github/workflows/helm.yml'
  workflow_dispatch:

jobs:
  publish-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: helm package helm/scubaclub

      - name: Create Helm repo index
        run: helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.repository }}

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
